### ISSUE TITLE
support capf completion-at-point-functions in Emacs

### ISSUE THREAD

**Issue by widp** [supercollider/scel#2]
_From @stardiviner on October 11, 2016 2:39_

I found `sclang-complete-symbol` does not compatible with Emacs new built-in `completion-at-point-functions`. When I set like this:

``` elisp
(setq completion-at-point-functions '(sclang-complete-symbol))
```

It will popup a completion buffer `*SCLang:Completions*`. And Emacs also show warning info in minibuffer:

```
Warning: sclang-complete-symbol failed to return valid completion data!
```

And because `company-mode` has a backend called `company-capf` for `completion-at-point-functions`. Most people now use `company-mode`.

So really hope to imporve `sclang-complete-symbol` to support `completion-at-point-functions`.

_Copied from original issue: supercollider/supercollider#2393_

**Comment by widp** [comment]
_From @stardiviner on May 17, 2017 1:47_

Is there any new progress on this?

**Comment by widp** [comment]
_From @snappizz on May 17, 2017 3:21_

Sorry, but scel is not very actively maintained :(

**Comment by widp** [comment]
_From @stardiviner on May 17, 2017 4:35_

I see, I'll try to dive in at some time. Thanks.

**Comment by stardiviner** [comment]
Hi, dear @widp , any update on this?

**Comment by derekxkwan** [comment]
Haven't dug into the code for `scel` and I've just switched from `auto-complete` to `company-mode` so I'm not quite sure if this is really the right way to do this or if this is helpful at all but... 

I came across [this link](http://sixty-north.com/blog/writing-the-simplest-emacs-company-mode-backend) for creating a simple company backend and basically replaced `'company-sample-backend` with `company-sclang-backend`, `'fundamental-mode` with `'sclang-mode`, and instead of `sample-completions` to populate the candidates, used the `sclang-mode` -provided `sclang-symbol-table`.

There's probably better ways of doing it (and should I be using something other than `sclang-symbol-table` to populate the candidates?) but seems to be working ok so far...

**Comment by widp** [comment]
@stardiviner 
Sorry about the late response, I've been busy so haven't been able to devote much time to this.
@derekxkwan 
The "right way" to do this would be to rewrite the function sclang-complete-symbol in sclang-language.el in about the same way that you've done - 
```
(defun sclang-complete-symbol (&optional predicate)
   (interactive)
  (let* ((bounds (bounds-of-thing-at-point 'word))
                  (sclang-completion-list (sclang-get-symbol-completion-table)))
    (when bounds
      (list (car bounds)
            (cdr bounds)
            sclang-completion-list))))
```
This is a very rudimentary function which does this, adding this to the completion-at-point-functions hook with -
```(add-hook 'completion-at-point-functions #'sclang-complete-symbol ) ``` should give you the same effect while using the thing-at-point library which comes with emacs instead of something company specific.

The above code is still missing method and class specific completion which I am currently looking into (So instead of giving you a list of methods for "SinOsc.", i.e. ar, ar1 etc. , it just gives you all the symbols).

**Comment by TatriX** [comment]
I'd like to make a PR for this feature unless it's already in progress.
