### ISSUE TITLE
Duplicate Document class when both IDE and scel are installed

### ISSUE THREAD

**Issue by widp** [supercollider/scel#3]
_From @mortuosplango on December 27, 2013 17:22_

As 5033eb36f77428a5734ff00df04a2ec1af8367b6 moves the Document class into the scel directory, it's not possible to use both in parallel anymore it seems.

_Copied from original issue: supercollider/supercollider#1014_

**Comment by widp** [comment]
_From @muellmusik on December 27, 2013 18:47_

With the new Document implementation and focus on scide it seemed best to untangle the Document cluster class / subclass design. The move of the old class was to maintain compatibility for scel users. I asked for comment from scel people at the time, but nobody said anything.

Running both in parallel from the same class lib seems to me an exotic choice. If somebody wants to work on a solution for that with scel, then fine, but otherwise I think this should be closed.

**Comment by widp** [comment]
_From @sensestage on December 28, 2013 0:51_

Hiho,

if put into proper ide-dependent directories, there should be no clash.

so:

scide_scqt/Document.sc for the new IDE version
scide_scel/Document.sc for the scel version

sincerely,
Marije

**Comment by widp** [comment]
_From @muellmusik on December 28, 2013 7:45_

The naming of those seem rather odd, or? scide is generally understood as the ide, which is only qt. What is scide_scel? Does it not use qt?

**Comment by widp** [comment]
_From @jamshark70 on December 28, 2013 7:49_

The scide_ prefix (for library compilation) was introduced long before there was ScIDE (the app).

scide_scel is for class definitions that support SuperCollider-Emacs-Lisp.

**Comment by widp** [comment]
_From @muellmusik on December 28, 2013 8:10_

I see. Would be preferable to change it. IAC, since I can't test on scel, I'll leave this to somebody else to deal with.

**Comment by widp** [comment]
_From @jamshark70 on December 28, 2013 8:15_

What to change it to? Maybe "editor_scel" and "editor_scide"?

**Comment by widp** [comment]
_From @muellmusik on December 28, 2013 8:35_

Yes, better.

**Comment by widp** [comment]
_From @timblechmann on December 28, 2013 8:43_

the `scide_` prefix might be used in (private) extensions.

**Comment by widp** [comment]
_From @danstowell on December 28, 2013 10:14_

`editor_` is not better, it's definitely worse - it's relatively likely that people will make folders beginning with that string, and find their folders mysteriously excluded from class compilation. This was a consideration when I decided on `scide_` a long time ago before ScIDE existed.

**Comment by widp** [comment]
_From @muellmusik on December 28, 2013 12:33_

Why not just scel, scide, scvim, etc.?

**Comment by widp** [comment]
_From @sensestage on January 4, 2014 13:12_

Hiho,

I imagine that may make it harder to filter for it.

I'm also not sure breaking the backwards compatibility is worth a
change.

sincerely,
Marije

**Comment by widp** [comment]
_From @jamshark70 on January 17, 2017 0:37_

Pinging this issue. editors/scel/README.md confidently states:

```
SuperCollider files are put in

`$prefix/share/SuperCollider/Extensions/scel`
```

But, we've known for over three years, as Marije pointed out, that it should be `$prefix/share/SuperCollider/Extensions/scide_scel` (or perhaps rather in the user's extension directory -- $prefix/share is Linux-specific).

This has tripped up a user who posted on Facebook about being unable to use ScIDE after installing scel.

**Comment by widp** [comment]
_From @brianlheim on January 17, 2017 0:58_

@jamshark70 Thanks for pinging -- could you open a PR? If it's just a matter of changing that line I can do it myself.

**Comment by widp** [comment]
_From @jamshark70 on January 17, 2017 3:39_

I don't know if it's only that. I can confirm that copying the class files under scide_scel avoids the duplicate class when running from ScIDE. My old scel configuration is far out of repair, so I'm not able to test right now whether anything else is needed (although the user on Facebook says that this was the only thing wrong).

**Comment by widp** [comment]
I can confirm that starting a server either from scel or from scide  and communication with s.sendMsg works.

**Comment by cicerojones** [comment]
@widp Hi, I'm confused by this thread. 

I'm on macOS 10.12 and, upon trying to start "Supercollider.app" (i.e. *not* via Emacs), I received the above `Duplicate Document class etc.` error, though I followed what I've assumed to be the "normal" procedure for installing scel, now that it is in its own submodule (which "normal procedure" btw, I'm basing on this blog post that presumably is a bit outdated itself now: http://www.rockhoppertech.com/blog/supercollider-with-emacs-on-osx/).

I inferred from @jamshark70 in the above discussion that

> copying the class files under scide_scel

meant to create a `scide_scel` directory alongside the `scide_scqt` directory within SCClassLibrary and then copy to this newly created directory *all* the files that I had originally copied from `scel/sc` to `Extensions`. Now, having done so, I am able to run Supercollider via the typical macOS "/Applications/Supercollider.app" interaction. 

But are these steps required by everyone? Was something actually fixed in this repo apropos of this issue? I notice that the README here on Github says that the files should be placed here (which path of course assumes a Linux box): `$prefix/share/SuperCollider/Extensions/scide_scel`, so I get the feeling I am doing something wrong, even though everything now seems to be working 😕 

Perhaps there's something that can be added to https://github.com/supercollider/scel#installation-default and https://github.com/supercollider/scel#installation-detailed to account for problems installing on Mac?

Thanks!

**Comment by widp** [comment]
@cicerojones I am not sure how you could be getting the error, especially since there is only one Document class which is used by the emacs package now. 
Are you sure you are not installing two versions of  scel? Check to see if you have an scide_scel folder in your Extensions directory.
